# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Website
title: "git-gud.sh"
description: ""
baseurl: ""
url: "https://nipanga.github.io"
email: "jotafelipe@gmail.com"


# Third PParty Services
twitter_username: realnipanga
github_username:  nipanga
google_analytics: UA-97046781-1

# Pagination Settings
paginate: 15
paginate_path: "page/:num/"

# Comments Settings - Disqus
disqus_short_name: "nipanga-github-io"
disqus_url: "https://nipanga-github-io.disqus.com"

# Authors Info
authors:
    nipanga:
        name: Juliano A. Felipe
        url: https://twitter.com/realnipanga

        
# Build Settings
markdown: kramdown
theme: jekyll-theme-hacker

# Kramdown Code Block Syntax Highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
      disable: false
    block:
      line_numbers: true
      start_line: 1
    
# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

